service: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

# package:
#   individually: true

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(iam/auctions-table-iam.yml):AuctionsTableIAM}

resources:
  # we are now in AWS world
  Resources:
    AuctionsTable: ${file(resources/auctions-table.yml):AuctionsTable}
          
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
    # package:
    #   exclude:
    #     - node_modules/**
    #     - package*json

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  bundle:
    linting: false
